services: 
  api:
    build: .
    depends_on:
      - postgres
    ports: 
      - '8000:8000'
    # bind mount
    volumes:
      - ./:/usr/src/app:ro 
      #ro = read only, container cant change file
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    # env_file:
    #   - ./.env
    environment:
    - DTB_HOSTNAME=postgres
    - DTB_PORT=5432
    - DTB_PWD=pwd123
    - DTB_NAME=fastapi
    - DTB_USERNAME=postgres
    - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    - ALGORITHM=HS256
    - ACCESS_TOKEN_EXPIRE_MINUTES=60    
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: pwd123
      POSTGRES_DB: fastapi

    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db: